### ISSUE TITLE
時刻毎に挨拶の表記を変えたい。

### ISSUE THREAD

**Issue by gotokaka** [gotokaka/SpringPractice#1]
# 概要

取得する現在時刻の時間帯によって、表示される挨拶が変わるように表示したい。
6〜12→「おはよう」
12〜18→「こんにちわ」
18〜24→「こんばんわ」
0〜6→「おやすみ」

https://github.com/gotokaka/SpringPractice/blob/e1ef70f32d2746b79f5a781da540ca2ae8f966ec/src/main/java/com/example/sample1/HelloWorldSpringController.java#LL16C2-L25C1

# 実行したこと。考えたこと。
-if文で時刻毎に表示できないか検索する。
-`ZoneId`メソッドとか出てきたけど多分違う。
-あまりスッキリするものがなかった
-時刻表示はString型。int型に型変換しなければならないのか？
-時刻は"yyyy/MM/dd HH:mm"で表されるが、例えば"HH"の部分だけを取り出して条件分岐するということはできないのか？出来ても大変そう。

**Comment by gotokaka** [comment]
# 変更1
-メソッド名の変更
168682bd4d8a82ac39be2a642607abc877819146
提出した課題に合わせて。



e604e89492ef76437180d8e74a16d44af1e51bb0
一気に書き換えてしまったので、要点をまとめる。
-国毎の挨拶にはしないので、`country`変数を削除
-`getCountry`メソッド、`setCountry`メソッドの削除
-`MessageWithTime`変数を`greetingMessage`へ書き換え。
-if文を`TimeUtils`クラスへ移動。
-`@RequestParam`アノテーションメソッドを削除

#### 実行結果
<img width="670" alt="スクリーンショット 2023-05-17 17 35 09" src="https://github.com/gotokaka/SpringPractice/assets/120085564/5d98e585-40a3-41f6-8029-a6348b8a3c46">

**Comment by gotokaka** [comment]
# 変更２
変更１の実行結果の`”greetingMessage”:”こんにちは！”`の表示はいらないので表示しないように変更を加えた。

05700648fc3feca186b76a3109511f2f93bf12bd

-`greeting`クラスの`greetingMessage`に関する変数とメソッドをコメントアウト。

-Controllerクラスの、`getter`,`setter`部分も`greetingMessage`から`message`へ変更。

-`TimeUtils`クラスの`getter`とif文の中身処理の変数名も`greetingMessage`からmessageへ変更。


#### 実行結果
<img width="277" alt="スクリーンショット 2023-05-18 13 34 25" src="https://github.com/gotokaka/SpringPractice/assets/120085564/87a25a09-75ae-4000-8ab1-98b9542bab3b">

当初イメージしていた通りに表示できました。

**Comment by TomooAkamatsu** [comment]
ひとまず、動くところまで持って行けたので素晴らしいですね！

 utilsクラスのインスタンスが生成されるのは違和感があるので、staticメソッドにしてしまって良いと思います。
現在時刻の変数はControllerで宣言した上で、それぞれのstaticメソッドを呼び出してあげた方がしっくりくるかな...と。

変数名は、
- currentDateTime→getTimeMessage 
- getMessage→getGreeting
のほうがわかりやすいかなと思いました！

また、現時点ではひとまず問題ないですが、ControllerクラスよりかはSeviceクラスで書くべき内容ではあります。

**Comment by gotokaka** [comment]
基礎的な理解不足で中々上手く行きません…。

49391a3cd770b806dd372417a1ea213313074df7

実行したこと。
-変数名変更しました。
-TimeUtilsクラスがあることが違和感があるので、TimeUtilsクラスの中身を諸々Controllerクラスに持ってくるということなのだと思い実行。staticメソッドにということは、インスタンス生成しなくてもいいようにControllerクラスに持ってくることだと思って試みました。出来ませんでした。
-コード自体に理解が足りなかったので分かったところだけコメントで残してみました。
-Serviceクラスについては簡単に調べてそういうものがあるのだとだけ認識しました。


質問：もしかして、(今回の場合は)TimeUtilsクラスは残してもいいが、日時取得の部分はControllerクラスに持ってくるように書き換えるということなのでしょうか？

お手数おかけしますがよろしくお願いいたします。



追記：現在インスタンスメソッドになっているものをstatic(クラス)メソッドにする時にどういう書き換えになるのか(また、その逆)という点を考えるべきなのでしょうか？

**Comment by TomooAkamatsu** [comment]
staticメソッド化については私の想像通り修正できています👍

> 質問：もしかして、(今回の場合は)TimeUtilsクラスは残してもいいが、日時取得の部分はControllerクラスに持ってくるように書き換えるということなのでしょうか？

 `LocalDateTime nowTime = LocalDateTime.now();`の部分だけControllerに持ってきてくれればOKです！

**Comment by gotokaka** [comment]
ありがとうございます！修正しました！
上手く動いたので確認お願い致します！


1f27cb0913278393d2b0586e8879f9d6c7dafe58


### 実行したこと・経過
-`LocalDateTime nowTime = LocalDateTime.now();`をControllerクラスへ移す。
<img width="1237" alt="スクリーンショット 2023-05-19 22 40 29" src="https://github.com/gotokaka/SpringPractice/assets/120085564/25265616-6bbb-4814-958a-7efe1c731b98">
ただ動かすだけだと、`formattedTime`変数の行がエラーになる。
-TimeUtilsクラス`getTimeMessage`の引数に`LocalDateTime nowTime`を入れる
-Controllerクラス`formattedTime`変数の右辺 `TimeUtils.getTimeMessage`の引数に`nowTime`を入れる
上記の様に引数を入れたら解消した。(理屈は分からないので今後の課題です。)

**Comment by TomooAkamatsu** [comment]
確認しました！
イメージとしてはそんな感じですね！

getGreetingも、
nowTime自体を引数で渡してあげて、
`int hour = nowTime.getHour();`で時刻を取得すればいいと思います。(以前formatとかややこしいこといってすみません🙏)

**Comment by gotokaka** [comment]
遅くなりすみません！！修正しました！ご確認お願い致します！！

88681837d9ecd6795c407800712a223676c7fe86

### 実行した事
-`TimeUtils`クラスの`getGreeting`メソッドの書き換えしました。
-`getGreeting`メソッドの引数に`nowTime`を渡す。
-`hour`変数を`parseInt`から`getHour`へ変更。
-`Controller`クラス18行目の引数に`nowTime`を渡す。

#### 実行結果
<img width="443" alt="スクリーンショット 2023-05-20 23 47 37" src="https://github.com/gotokaka/SpringPractice/assets/120085564/e2a9c249-da58-4b09-b6a7-23578136681e">


上手くいきました。


`LocalDateTime`クラスへの理解が足りなかったので再度調べました。[参考](https://flytech.work/blog/11832/)
赤松さんが仰った通り、getHourメソッドだけでも部分的に取得できることがわかりました。勉強になりました！！

formatはそれはそれで勉強になったので大丈夫です！ありがとうございます！
